# Site
repository: shaonianruntu/shaonianruntu.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: æ–¹æ¥ 
title: è®¡ç®—æœºç§‘å­¦ä¸æŠ€æœ¯ç¡•å£«å­¦ä½åœ¨è¯»
email: fangnan97@qq.com
# website: shaonianruntu.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: shaonianruntu
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: fangnan97
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
#   - title: itsgoingto.be
#     icon: fas fa-globe
#     url: https://www.itsgoingto.be
#   - title: another link
#     icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#     url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/user.jpg
about_content: | # this will include new lines to allow paragraphs
  ä½ å¥½ğŸ‘‹ï¼Œæˆ‘æ˜¯æ–¹æ¥ ã€‚æˆ‘æ¥è‡ªäºä¸­å›½ä¸Šæµ·ã€‚ç°åœ¨æ˜¯æˆ‘åœ¨æ­å·ç”µå­ç§‘æŠ€å¤§å­¦æ”»è¯»æˆ‘çš„è®¡ç®—æœºç§‘å­¦ä¸æŠ€æœ¯å­¦æœ¯å‹ç¡•å£«æ–‡å‡­å­¦ä½çš„ç¬¬äºŒå¹´ã€‚

  Hi, my name's Nan Fang æ–¹æ¥ . I am from Shanghai, China. I'm a first-year postgraduate student at the School of Computer Science, Hangzhou Dianzi University. And I am a person who has a strong desire for knowledge. I like to explore new things and have a team spirit. As well as machine learning and computer vision I also have experience making software and web apps. I have worked at a number of labs gaining teamwork and leadership skills.

  I am skilled in: <mark>Python</mark> <mark>Pytorch</mark> <mark>React</mark> <mark>Laravel</mark> <mark>C++</mark> and <mark>MySQL</mark>.

  And I am proficient in using: <mark>VSCode</mark> <mark>XCode</mark> <mark>Office</mark> <mark>macOS</mark> <mark>Ubuntu</mark> and <mark>Windows</mark>. 

  At the same time, I also have language skills of: <mark>CET-6</mark> <mark>CET-4</mark>.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: åŸºäºç”¨æˆ·è¡Œä¸ºåˆ†æçš„æ™ºèƒ½å®¶å±…èŠ‚èƒ½ç³»ç»Ÿ
        sub_title: å›½å®¶çº§å¤§å­¦ç”Ÿåˆ›æ–°åˆ›ä¸šé¡¹ç›®
        caption: 2018å¹´5æœˆè‡³2019å¹´6æœˆ

      - layout: left
        title: åŸºäºç”¨æˆ·è¡Œä¸ºåˆ†æçš„æ™ºèƒ½å®¶å±…èŠ‚èƒ½ç³»ç»Ÿ
        sub_title: å›½å®¶çº§å¤§å­¦ç”Ÿåˆ›æ–°åˆ›ä¸šé¡¹ç›®
        caption: 2018å¹´5æœˆè‡³2019å¹´6æœˆ
        # link: github.com/sproogen
        # link_text: Project Website
        # additional_links:
        #   - title: sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
        # - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #   icon: fab fa-github
        #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          è¯¥é¡¹ç›®ä¸»è¦æ¶‰åŠåŸºäº C/C++ è¯­è¨€çš„ STM32 ARM èŠ¯ç‰‡æ§åˆ¶ç®—æ³•ã€ç‰©è”ç½‘ç½‘å…³åè®®ï¼Œç”µå­é›†æˆç”µè·¯è®¾è®¡ï¼ŒåŸºäº Python è¯­è¨€çš„æ ‘è“æ´¾æ§åˆ¶ç®—æ³•ï¼Œç»“åˆ MySQL æ•°æ®åº“çš„ç”¨æˆ·è¡Œä¸ºåˆ†æ AI æœºå™¨å­¦ä¹ ç®—æ³•ã€‚
        description: |
          æœ¬é¡¹ç›®ä¸»è¦å¼€å‘äº†ä¸€ç§åŸºäºç”¨æˆ·è¡Œä¸ºåˆ†æçš„æ™ºèƒ½å®¶å±…èŠ‚èƒ½ç³»ç»Ÿã€‚ä½¿ç”¨é¢„æµ‹ç®—æ³•å®ç°å¯¹ç”¨æˆ·å®¶ç”µä½¿ç”¨è¡Œä¸ºçš„é¢„æµ‹ï¼Œæå‡ºä¸€ç§å®¤å†…å®¶ç”µè¿è¡Œè°ƒåº¦ç®—æ³•ï¼Œåœ¨ä¿éšœç”¨æˆ·èˆ’é€‚åº¦çš„å‰æä¸‹ï¼Œé€šè¿‡å¯¹ç”µå™¨è¿ä½œçŠ¶æ€çš„åŠ¨æ€è§„åˆ’ï¼Œæœ‰æ•ˆæé«˜èƒ½æºçš„åˆ©ç”¨æ•ˆç‡ï¼Œå‡å°‘ç”¨æˆ·çš„ç”µåŠ›æ”¯å‡ºï¼Œè¾¾åˆ°èŠ‚èƒ½çš„ç›®çš„ã€‚

          ä¸ºäº†å®ç°å¯¹å®¶ç”¨ç”µæ°”çš„éä¾µå…¥å¼çŠ¶æ€æ£€æµ‹å’Œæ•´å±‹å®¶ç”¨ç”µæ°”çš„å…¨å±€çŠ¶æ€åˆ†æï¼Œæˆ‘ä»¬è‡ªè¡Œç ”å‘äº†ä¸€æ¬¾åŸºäºæ— çº¿æ™ºèƒ½ç½‘å…³çš„æ™ºèƒ½å®¶å±…èŠ‚èƒ½ç³»ç»Ÿï¼Œé€šè¿‡é‡‡ç”¨èƒ½è€—é‡‡é›†æ¨¡å—å’Œä¼ æ„Ÿå™¨ç›‘æµ‹æ¨¡å—å¯¹ç”µå™¨çš„ç”¨ç”µæƒ…å†µå’Œä½¿ç”¨ç¯å¢ƒä¿¡æ¯è¿›è¡Œé‡‡é›†ï¼Œåœ¨æœ¬åœ°èŠ‚ç‚¹å¯¹ç”µå™¨èƒ½è€—ä¿¡æ¯è¿›è¡Œç®€å•çš„å¤„ç†åï¼Œé€šè¿‡ZigBeeæ— çº¿é€šä¿¡æ¨¡å—å°†ç”¨ç”µæƒ…å†µå‘é€ç»™æ™ºèƒ½ç½‘å…³è¿›è¡Œç”µå™¨è¯†åˆ«å’Œç”¨æˆ·è¡Œä¸ºåˆ†æå­¦ä¹ ï¼Œå¹¶å°†è®¡ç®—å‡ºæ¥çš„æ§åˆ¶ä¿¡æ¯åé¦ˆç»™æ§åˆ¶æ¨¡å—ï¼Œå¯¹ç”µå™¨çŠ¶æ€è¿›è¡Œç›¸åº”çš„æ™ºèƒ½æ§åˆ¶ã€‚åŒæ—¶ï¼Œå°†ç”µå™¨çš„èƒ½è€—ä¿¡æ¯å’Œæ“ä½œçŠ¶æ€é€šè¿‡äº‘å¹³å°åé¦ˆç»™ç”¨æˆ·ã€‚

          åŸºäºè¯¥é¡¹ç›®ï¼Œæˆ‘ä»¬è¿˜å‘è¡¨æœ‰ä¸¤ç¯‡è®¡ç®—æœºè½¯ä»¶è‘—ä½œï¼šã€ŠåŸºäºç”¨æˆ·è¡Œä¸ºåˆ†æçš„æ™ºèƒ½å®¶å±…èŠ‚èƒ½ç³»ç»ŸV1.0ã€‹å’Œã€Šç”µå™¨è¯†åˆ«å¯è§†åŒ–ç³»ç»ŸV1.0ã€‹ã€‚

          åŒæ—¶ï¼Œæˆ‘ä»¬ä¹Ÿæä¾›äº†è¯¥æ™ºèƒ½è°ƒèŠ‚ç³»ç»Ÿçš„æ¼”ç¤ºè§†é¢‘ï¼š[åŸºäºç”¨æˆ·è¡Œä¸ºåˆ†æçš„æ™ºèƒ½å®¶å±…èŠ‚èƒ½ç³»ç»Ÿ](https://www.bilibili.com/video/av27494462)ã€‚

      - layout: left
        title: åŸºäºè¯­éŸ³è¯†åˆ«çš„æ™ºèƒ½è€äººçœ‹æŠ¤ç³»ç»Ÿ
        sub_title: æµ™æ±Ÿçœæ–°è‹—äººæ‰è®¡åˆ’
        caption: 2017å¹´6æœˆè‡³2019å¹´10æœˆ
        quote: >
          è¯¥é¡¹ç›®ä¸»è¦æ¶‰åŠåŸºäº C/C++ è¯­è¨€çš„ STM32 ARM èŠ¯ç‰‡ã€å¾®èŠ¯ PLC18ã€STC51 èŠ¯ç‰‡å’Œæ ‘è“æ´¾çš„æ§åˆ¶ç®—æ³•ã€ç‰©è”ç½‘ç½‘å…³åè®®ï¼Œç”µå­é›†æˆç”µè·¯è®¾è®¡ï¼ŒåŸºäº JavaScript å’Œ JAVA è¯­è¨€çš„ç½‘ç«™å¼€å‘ï¼ŒåŸºäº MySQL è¯­è¨€çš„æ•°æ®åº“ï¼ŒåŸºäº Tensorflow è¯­è¨€çš„AIè‡ªç„¶è¯­è¨€å¤„ç†ç®—æ³•ã€‚
        description: |
          æœ¬é¡¹ç›®ä¸»è¦å¼€å‘äº†ä¸€ç§æ–°å‹åŸºäºè¯­éŸ³è¯†åˆ«çš„æ™ºèƒ½è€äººçœ‹æŠ¤ç³»ç»Ÿã€‚

          è¯¥ç³»ç»Ÿç”±æ™ºèƒ½ä¾¿æºå¼èƒ¸é’ˆå’Œæ™ºèƒ½å®¶åº­æ§åˆ¶ä¸­å¿ƒä¸¤éƒ¨åˆ†æ„æˆï¼Œæ™ºèƒ½èƒ¸é’ˆé™¤å®ç°åŸºæœ¬çš„è£…é¥°åŠŸèƒ½å¤–ï¼Œè¿˜èƒ½å¤Ÿå®ç°é˜²æ‘”å€’æé†’å’Œè·Œå€’æŠ¥è­¦ï¼Œå½“è€äººå°†è¦è·Œå€’æ—¶é€šè¿‡èƒ¸é’ˆä¸Šè‡ªå¸¦çš„æŠ¥è­¦æ¨¡å—å¯¹è€äººè¿›è¡Œé¢„è­¦æé†’ï¼›åˆ°è€äººè·Œå€’åœ¨åœ°éš¾ä»¥çˆ¬èµ·æ—¶ï¼Œé€šè¿‡æ™ºèƒ½å®¶åº­æ§åˆ¶ä¸­å¿ƒä»¥çŸ­ä¿¡çš„æ–¹å¼å®æ—¶å‘å­å¥³æŠ¥è­¦ã€‚é™¤æ­¤ä¹‹å¤–ï¼Œæ™ºèƒ½èƒ¸é’ˆè¿˜å…·æœ‰è¯­éŸ³ä¿¡å·é‡‡é›†çš„åŠŸèƒ½ï¼Œå°†é‡‡é›†åˆ°çš„ä¿¡å·é€šè¿‡æ— çº¿ä¼ è¾“åè®®å‘é€ç»™ä¸»æœºè¿›è¡Œå¤„ç†ã€‚

          æ™ºèƒ½å®¶åº­æ§åˆ¶ä¸­å¿ƒä¸»è¦åšçš„æ˜¯è¯­éŸ³ä¿¡å·å¤„ç†å’Œæ™ºèƒ½å®¶åº­æ§åˆ¶ï¼Œå¹¶æ·»åŠ è¿œç¨‹æ™ºèƒ½æ‘„åƒå¤´ï¼Œè®©å­å¥³èƒ½å¤Ÿå®æ—¶ç›‘æ§å®¶åº­å®‰å…¨ã€‚ä»æœºçš„æ— çº¿éº¦å…‹é£é˜µåˆ—é‡‡é›†åˆ°çš„ç»è¿‡å‰ç«¯é™å™ªå¤„ç†çš„è¯­éŸ³é€šè¿‡åœ¨ä¸»æœºä¸Šè¿›è¡Œæ±‰è¯­å£éŸ³è‡ªé€‚åº”å¤„ç†ã€éå‘½ä»¤è¯æ™ºèƒ½è¯­ä¹‰åˆ†æåå¾—åˆ°ç²¾ç¡®çš„æŒ‡ä»¤ä¿¡æ¯ï¼Œæ§åˆ¶ä¸»æœºå®ç°å¯¹äºç›¸åº”çš„æ™ºèƒ½å®¶å±…çš„æ§åˆ¶ã€‚

          åŸºäºè¯¥é¡¹ç›®ï¼Œæˆ‘ä»¬è¿˜å‘è¡¨æœ‰ä¸¤ç¯‡è®¡ç®—æœºè½¯ä»¶è‘—ä½œï¼šã€ŠåŸºäºè¯­éŸ³è¯†åˆ«çš„æ™ºèƒ½è€äººçœ‹æŠ¤ç³»ç»ŸV1.0ã€‹å’Œã€ŠåŸºäºæ— çº¿è‡ªç»„ç½‘åè®®çš„å®¶ç”µæ§åˆ¶ç³»ç»ŸV1.0ã€‹ã€‚

          åŒæ—¶ï¼Œæˆ‘ä»¬ä¹Ÿæä¾›äº†è¯¥æ™ºèƒ½è€äººçœ‹æŠ¤ç³»ç»Ÿçš„æ¼”ç¤ºè§†é¢‘ï¼š[åŸºäºè¯­éŸ³è¯†åˆ«çš„æ™ºèƒ½è€äººçœ‹æŠ¤ç³»ç»Ÿ](https://www.bilibili.com/video/av81282247)ã€‚

      - layout: left
        title: é˜²é›¾éœ¾ç©ºæ°”è°ƒèŠ‚æ™ºèƒ½ç›’å­
        sub_title: æ­å·ç”µå­ç§‘æŠ€å¤§å­¦èŠ¯è‹—äººæ‰è®¡åˆ’
        caption: 2016å¹´12æœˆè‡³2017å¹´12æœˆ
        quote: >
          è¯¥é¡¹ç›®è®¾è®¡åŸºäº C/C++ è¯­è¨€çš„ STM32 èŠ¯ç‰‡æ§åˆ¶ç®—æ³•ã€ç‰©è”ç½‘ç½‘å…³åè®®ï¼Œç”µå­é›†æˆç”µè·¯è®¾è®¡ã€‚
        description: |
          è¯¥é¡¹ç›®ä¸»è¦å¼€å‘äº†ä¸€æ¬¾å°ä½“ç§¯çš„å…·æœ‰é˜²é›¾éœ¾åŠŸèƒ½çš„ç©ºæ°”è°ƒèŠ‚æ™ºèƒ½ç›’å­ã€‚å…·æœ‰ç›‘æµ‹å®¤å†…å¤–æ¸©åº¦ï¼Œç©ºæ°”æ¹¿åº¦ï¼ŒäºŒæ°§åŒ–ç¢³æµ“åº¦ä»¥åŠé¢—ç²’ç‰©æµ“åº¦ç­‰åŠŸèƒ½ï¼Œå¹¶å¯ä»¥æ ¹æ®è¿™äº›æŒ‡æ ‡çš„ç›‘æµ‹ç»“æœå¯¹æ•°æ®è¿›è¡Œåˆ†æï¼Œä»è€Œå®ç°åˆ¤æ–­æ˜¯å¦å­˜åœ¨é›¾éœ¾ä»¥åŠé›¾éœ¾æµ“åº¦æµ‹é‡åŠŸèƒ½ã€‚åŒæ—¶ï¼Œå¦‚æœç›‘æµ‹åˆ°æœ‰é›¾éœ¾è¶…è¿‡ä¸€å®šé‡çš„æµ“åº¦ï¼Œç›’å­è¿˜å¯ä»¥è‡ªåŠ¨è°ƒèŠ‚é—¨çª—å¼€å…³ã€‚

      - layout: left
        title: åŸºäºSTM32çš„æ™ºèƒ½å„¿ç«¥çœ‹æŠ¤æ‰‹è¡¨
        sub_title: æ­å·ç”µå­ç§‘æŠ€å¤§å­¦èŠ¯è‹—äººæ‰è®¡åˆ’
        caption: 2016å¹´12æœˆè‡³2017å¹´12æœˆ
        quote: >
          è¯¥é¡¹ç›®è®¾è®¡åŸºäº C/C++ è¯­è¨€çš„ STM32 èŠ¯ç‰‡æ§åˆ¶ç®—æ³•ï¼Œç”µå­é›†æˆç”µè·¯è®¾è®¡ã€‚
        description: |
          è¯¥é¡¹ç›®ä¸»è¦å¼€å‘äº†ä¸€æ¬¾é›†å„¿ç«¥å¥åº·å’Œå®‰å…¨ä¸¤ä¸ªæ–¹é¢äºä¸€ä½“çš„æ™ºèƒ½å„¿ç«¥çœ‹æŠ¤æ‰‹è¡¨ï¼Œä»¥ STM32 MCU ä½œä¸ºä¸»æ§èŠ¯ç‰‡, ç»“åˆå¤–å›´ç”µè·¯å’Œå¤šç§ä¼ æ„Ÿå™¨åŠ ä»¥å®ç°ã€‚æ ¹æ®ç›‘æŠ¤äººçš„å®é™…éœ€æ±‚ï¼Œè¯¥è®¾è®¡æ¶µç›–è¿åŠ¨æ£€æµ‹ã€ç¯å¢ƒç›‘æµ‹ã€GPSå®šä½ã€SOSæŠ¥è­¦å››å¤§æ–¹å‘å¹¶ä¸”å…·æœ‰è®°å½•å„¿ç«¥è¿åŠ¨æ­¥æ•°ã€GPSé‡‡é›†è¿åŠ¨é‡Œç¨‹ã€æ—¶é—´å’Œé€Ÿåº¦ã€æ¸©æ¹¿åº¦æ£€æµ‹ã€é›¾éœ¾æ£€æµ‹å’ŒæŠ¥è­¦ã€è®°å½•æ´»åŠ¨è·¯ç¨‹ã€è®¾ç½®ç”µå­æ …æ è¶…å‡ºèŒƒå›´çŸ­ä¿¡é€šçŸ¥å®¶é•¿ã€ä¸€é”®å‘¼å«å®¶é•¿ã€å‘å®¶é•¿å‘é€ç‰¹å®šçŸ­ä¿¡ç­‰å¤šé¡¹åŠŸèƒ½ã€‚

          è¯¥æ™ºèƒ½å„¿ç«¥çœ‹æŠ¤æ‰‹è¡¨çš„è®¾è®¡å……åˆ†è€ƒè™‘äº†å­©å­ç›‘æŠ¤äººçš„å®é™…éœ€æ±‚ï¼Œå¹¶é€šè¿‡ç”µå­æŠ€æœ¯çš„æ–¹æ³•åŠ ä»¥è§£å†³ã€‚

      - layout: left
        title: æ—‹è½¬æ–‡å­—æ˜¾ç¤ºLED
        sub_title: æ­å·ç”µå­ç§‘æŠ€å¤§å­¦èŠ¯è‹—äººæ‰è®¡åˆ’
        caption: 2016å¹´6æœˆè‡³2016å¹´7æœˆ
        link: github.com/shaonianruntu/Rotating-LED
        link_text: Project Website
        quote: >
          è¯¥é¡¹ç›®è®¾è®¡åŸºäº C/C++ è¯­è¨€çš„ STM32 èŠ¯ç‰‡æ§åˆ¶ç®—æ³•ï¼Œç”µå­é›†æˆç”µè·¯è®¾è®¡ã€‚
        description: |
          è¯¥é¡¹ç›®ä¸»è¦å¼€å‘äº†å…·æœ‰ä¸­è‹±æ–‡ã€å­—ç¬¦ç¬¦å·å’Œæµæ°´èŠ±çº¹æ ·å¼æ˜¾ç¤ºåŠŸèƒ½çš„æ—‹è½¬LEDç¯ï¼Œåˆ©ç”¨äººçœ¼çš„è§†è§‰æ®‹ç•™æ•ˆåº”ï¼Œè‡ªåŠ¨è°ƒèŠ‚LEDç¯ç®¡çš„æ—‹è½¬å‘¨æœŸæ—¶é—´ï¼Œä»¥åˆ©ç”¨ä¸€æ ¹é«˜é€Ÿæ—‹è½¬çš„ç¯ç®¡å®ç°æ•´ä½“åœ†å‘¨é¢çš„ç”»é¢æ’ä¹…æ˜¾ç¤ºã€‚

          ä¸ºäº†å®ç°å¯¹äºLEDç¯ç®¡çš„è½¬é€Ÿä¸æ˜¾ç¤ºæ®‹ç•™æ—¶é•¿çš„ååŒæ§åˆ¶ï¼Œé€šè¿‡åœ¨LEDç¯ç®¡ä¸‹æ–¹å’Œå°ç¯åº•åº§ä¸Šæ–¹å®‰è£…çº¢å¤–å¯¹æ¥æ”¶å‘è®¾å¤‡ï¼ŒLEDç¯ç®¡ä¸Šçš„çº¢å¤–æ¥æ”¶ç®¡æ¯è½¬åŠ¨ä¸€åœˆå°±ä¼šå¯¼é€šä¸€æ¬¡ï¼Œè®©å•ç‰‡æœºçŸ¥é“ä»å“ªä¸€ç‚¹å¼€å§‹æ’­æ”¾å­—ç¬¦æˆ–è€…å›¾è±¡å…·æœ‰å¾ˆé«˜çš„æ¬£èµä»·å€¼ã€‚

          åŒæ—¶ï¼Œæˆ‘ä»¬ä¹Ÿæä¾›äº†è¯¥æ—‹è½¬æ–‡å­—æ˜¾ç¤ºLEDçš„å®ç°æºä»£ç å’Œç”µå­é›†æˆç”µè·¯è®¾è®¡ç‰ˆå›¾ï¼š[shaonianruntu/Rotating-LED](https://github.com/shaonianruntu/Rotating-LED) ä»¥åŠæ¼”ç¤ºè§†é¢‘ï¼š[æ—‹è½¬æ–‡å­—æ˜¾ç¤ºLED](https://www.bilibili.com/video/BV12s411K7yK)

          æœ¬é¡¹ç›®ä¸»è¦å¼€å‘äº†ä¸€ç§æ–°å‹åŸºäºè¯­éŸ³è¯†åˆ«çš„æ™ºèƒ½è€äººçœ‹æŠ¤ç³»ç»Ÿã€‚

  # - title: Experience # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: left
  #       title: The Boring Company
  #       link: boringcompany.com
  #       # link_text: boringcompany.com
  #       sub_title: Senior Network System Administrator
  #       caption: November 2017 - Present
  #       quote: >
  #         Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
  #       description: | # this will include new lines to allow paragraphs
  #         Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Hangzhou Dianzi University
        caption: 2019 - Present
        sub_title: MSc Computer Science
        quote: >
          Hangzhou Dianzi University (HDU) was founded in 1956. It is a comprehensive university and one of the best top 5 universities with its own distinctive features in the field of electronic science and technology, engineering and information technology as well as management and accounting,etc.
        description: | # this will include new lines to allow paragraphs
          During my time at HDU I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a laboratory member of the [**Media Intelligence Laboratory**](http://mil.hdu.edu.cn/) and doing research in computer vision.

      - layout: left
        title: Hangzhou Dianzi University
        caption: 2015 - 2019
        sub_title: BSc Computer Science
        quote: >
          Hangzhou Dianzi University (HDU) was founded in 1956. It is a comprehensive university and one of the best top 5 universities with its own distinctive features in the field of electronic science and technology, engineering and information technology as well as management and accounting,etc.
        description: | # this will include new lines to allow paragraphs
          During my time at HDU I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I joint the **Hangzhou Dianzi University Microchip Joint Technological Innovation Incubation Laboratory** in my freshman year. And after that I worked with the lab's team members to complete some projects, particated in some competitions, and achieved some good results. I am mainly repsonible for some code writing work in the team projects and taking on role as **Head of Software Group**. In my laboratory time, I led my team members finshed **four college-level new seedling project**, **one provincial-level new seedling talent project**, **one national-level university student innovation and entrepreneurship project** as the role of team leader of these projects, and published a total of **four computer software copyrights**. 

          The experience in the laboratory allowed me to be in touch with some research projects and related professional knowledge earlier than other students. It also broadened my horizons and improved my self-learning ability and information gathering ability.

      - layout: left
        title: Zhejiang Yuyao High School
        caption: 2012 - 2015
        quote: >
          Zhejiang Yuyao High School is a key high school located in Yuyao City, Ningbo City, China.

          Founded in 1935, the school is the first middle school in the history of Yuyao. It was only the junior school when it was first built, and opened in 1943. In 1961, the school became a pilot high school in Zhejiang Province. In 1981, it became a key high school in Zhejiang Province. After 1989, it became a special high school. In 1995, it became a primary key high school in Zhejiang Province.
        description: | # this will include new lines to allow paragraphs

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in machine learing and software engineering some of my other interests and hobbies are:
      - Classical literture & Swordsman fiction
      - Historical drama & Costume drama
      - Drive & Travel

      This is my Douban account [shaonianruntu](https://www.douban.com/people/shaonianruntu/). If you have the same interest, maybe we can be a book friend.

      Here is the link to some of my friends' homepages, maybe you will be interested:
        - [é«˜é£è€å¸ˆ](https://fei-hdu.github.io/)
        - [ç½—å®‡çŸ—åŒå­¦](https://www.luoyuchu.com/)
        - [å¶å®¶è±ªåŒå­¦](https://yjhmelody.github.io/)
        - [æ›¹éªå¨å­¦å¼Ÿ](https://accepteddoge.com/)
        - [æŸ³å©¼å­¦å§](https://www.liuchuo.net/)

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
