# Site
repository: shaonianruntu/shaonianruntu.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: æ–¹æ¥ 
title: è®¡ç®—æœºç§‘å­¦ä¸æŠ€æœ¯ç¡•å£«å­¦ä½åœ¨è¯»
email: fangnan97@qq.com
# website: shaonianruntu.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: shaonianruntu
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: fangnan97
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb

# Additional icon links
# additional_links:
#   - title: itsgoingto.be
#     icon: fas fa-globe
#     url: https://www.itsgoingto.be
#   - title: another link
#     icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#     url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/user.jpg
about_content: | # this will include new lines to allow paragraphs
  ä½ å¥½ğŸ‘‹ï¼Œæˆ‘æ˜¯æ–¹æ¥ ã€‚æˆ‘æ¥è‡ªäºä¸­å›½ä¸Šæµ·ã€‚ç°åœ¨æ˜¯æˆ‘åœ¨æ­å·ç”µå­ç§‘æŠ€å¤§å­¦æ”»è¯»æˆ‘çš„è®¡ç®—æœºç§‘å­¦ä¸æŠ€æœ¯ä¸“ä¸šå­¦æœ¯ç¡•å£«æ–‡å‡­å­¦ä½çš„ç¬¬äºŒå¹´ã€‚æˆ‘æ˜¯ä¸€ä¸ªå¯¹çŸ¥è¯†æœ‰å¼ºçƒˆæ¸´æœ›çš„äºº,æˆ‘å–œæ¬¢æ¢ç´¢æ–°äº‹ç‰©å¹¶å…·æœ‰å¾ˆå¼ºçš„å›¢é˜Ÿåˆä½œç²¾ç¥ã€‚é™¤äº†åœ¨æ·±åº¦å­¦ä¹ å’Œè®¡ç®—æœºè§†è§‰çš„ä¸“ä¸šæŠ€èƒ½ä¹‹å¤–ï¼Œæˆ‘è¿˜å…·æœ‰åµŒå…¥å¼è½¯ä»¶å¼€å‘ã€ç§»åŠ¨ç«¯è½¯ä»¶å¼€å‘å’Œç½‘é¡µå‰ç«¯å¼€å‘çš„èƒ½åŠ›ã€‚åŒæ—¶ï¼Œæœ¬ç§‘å’Œç ”ç©¶ç”ŸæœŸé—´åœ¨å­¦æ ¡å®éªŒå®¤å’Œç¤¾å›¢å·¥ä½œçš„ç»å†ï¼Œä½¿æˆ‘ç§¯ç´¯äº†å¤§é‡çš„é¡¹ç›®ç ”å‘ç»éªŒå’Œå›¢é˜Ÿåˆä½œé¢†å¯¼ç»éªŒã€‚

  æˆ‘å…·æœ‰å¦‚ä¸‹ä¸“ä¸šæŠ€èƒ½ï¼š<mark>C/C++</mark> <mark>Python</mark> <mark>Pytorch</mark> <mark>html/css</mark> <mark>JavaScript</mark> å’Œ <mark>MySQL</mark>.

  å¹¶ä¸”ï¼Œæˆ‘èƒ½å¤Ÿç†Ÿç»ƒçš„ä½¿ç”¨ï¼š<mark>VSCode</mark> <mark>Clion</mark> <mark>Keil</mark> <mark>Office</mark> <mark>Ubuntu</mark> <mark>macOS</mark> å’Œ <mark>Windows</mark>. 

  åŒæ—¶ï¼Œæˆ‘ä¹Ÿå…·æœ‰ <mark>CET-6</mark> å’Œ <mark>CET-4</mark> çš„å¤–è¯­è‹±è¯­è¯­è¨€æŠ€èƒ½ã€‚

content:
  - title: é¡¹ç›®ç»å† # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: è‹±è¯­é€‰è¯å¡«ç©ºæ™ºèƒ½ä½œç­”æœºå™¨äºº
        sub_title: æ­å·ç”µå­ç§‘æŠ€å¤§å­¦æœ¬ç§‘ç”Ÿæ¯•ä¸šè®¾è®¡
        caption: 2018å¹´12æœˆè‡³2019å¹´6æœˆ
        quote: >
          æœ¬é¡¹ç›®ä¸»è¦æ¶‰åŠåŸºäº JavaScript å’Œ JAVA è¯­è¨€çš„å¾®ä¿¡å°ç¨‹åºå‰åç«¯å¼€å‘ï¼ŒåŸºäº MySQL è¯­è¨€çš„æ•°æ®åº“ï¼ŒåŸºäº Tensorflow è¯­è¨€çš„AIè‡ªç„¶è¯­è¨€å¤„ç†ç®—æ³•ï¼ŒåŸºäº Pytorch è¯­æ³•çš„AIå›¾åƒæ–‡å­—è¯†åˆ«ç®—æ³•ã€‚
        description: |
          æœ¬é¡¹ç›®ä¸»è¦å¼€å‘äº†ä¸€æ¬¾åŸºäºè¯­è¨€æ¨¡å‹ç®—æ³•å’Œå¾®ä¿¡å°ç¨‹åºå¼€å‘å¹³å°çš„è‹±è¯­é€‰è¯å¡«ç©ºå’Œå•é¡¹é€‰æ‹©è‡ªåŠ¨æ™ºèƒ½ä½œç­”è½¯ä»¶ã€‚

          åœ¨å¾®ä¿¡å°ç¨‹åºè½¯ä»¶å¼€å‘è¿‡ç¨‹ä¸­ï¼Œæˆ‘ä»¬é‡‡ç”¨äº†â€œå¾®ä¿¡å°ç¨‹åºå®¢æˆ·ç«¯+å¾®ä¿¡å°ç¨‹åºäº‘å¹³å°+äº‘æœåŠ¡å™¨â€çš„è‡ªä¸»è½¯ä»¶è®¾è®¡æ¶æ„ï¼Œåœ¨å¾®ä¿¡å°ç¨‹åºå®¢æˆ·ç«¯å®ç°åŸºæœ¬çš„è½¯ä»¶äº¤äº’é€»è¾‘ï¼›åœ¨å¾®ä¿¡å°ç¨‹åºäº‘å¼€å‘å¹³å°ä¸Šå®ç°äº‘å‡½æ•°è°ƒç”¨ã€äº‘æ•°æ®åº“ç®¡ç†å’Œäº‘å­˜å‚¨åŠŸèƒ½ï¼›åœ¨äº‘æœåŠ¡å™¨ä¸­å®ç°å¯¹è‹±è¯­é€‰è¯å¡«ç©ºå¥å­å’Œå•é¡¹é€‰æ‹©é¢˜ç›®çš„åŸºäº N-Gram è¯­è¨€æ¨¡å‹çš„å¥å­ç»„åˆæ–¹å¼ AI è¯„ä¼°ï¼Œå¾—åˆ°æœ€ä¼˜è§£ç­”åºåˆ—ï¼Œå¹¶è¿”å›ç»™å¾®ä¿¡å°ç¨‹åºè¿›è¡Œæ˜¾ç¤ºã€‚

          é€šè¿‡ä½¿ç”¨æˆ‘ä»¬è‡ªè¡Œè®¾è®¡çš„â€œå¾®ä¿¡å°ç¨‹åºå®¢æˆ·ç«¯+å¾®ä¿¡å°ç¨‹åºäº‘å¹³å°+äº‘æœåŠ¡å™¨â€çš„ä¸‰çº§è½¯ä»¶è®¾è®¡æ¶æ„ï¼Œå¯ä»¥çªç ´å¾®ä¿¡å°ç¨‹åºå®¢æˆ·ç«¯åœ¨å¯¹äºè½¯ä»¶è§„æ¨¡ã€è½¯ä»¶åŠŸèƒ½ä¸Šçš„é™åˆ¶ï¼Œç®€åŒ–æˆ‘ä»¬å¾®ä¿¡å°ç¨‹åºçš„å‰ç«¯æ¶æ„ï¼Œæé«˜æˆ‘ä»¬åç«¯åœ¨è®¾è®¡ä¸Šçš„è‡ªç”±åº¦å’Œè½¯ä»¶åç»­ç‰ˆæœ¬æ›´æ–°çš„ä¾¿æ·åº¦å’Œå¯æ‰©å±•æ€§ã€‚ä¾¿äºæˆ‘ä»¬è½¯ä»¶çš„ç»´æŠ¤ã€å‡çº§å’ŒäºŒæ¬¡é‡æ„ã€‚

      - layout: left
        title: åŸºäºç”¨æˆ·è¡Œä¸ºåˆ†æçš„æ™ºèƒ½å®¶å±…èŠ‚èƒ½ç³»ç»Ÿ
        sub_title: å›½å®¶çº§å¤§å­¦ç”Ÿåˆ›æ–°åˆ›ä¸šé¡¹ç›®
        caption: 2017å¹´5æœˆè‡³2018å¹´12æœˆ
        # link: github.com/sproogen
        # link_text: Project Website
        # additional_links:
        #   - title: sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
        # - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #   icon: fab fa-github
        #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          æœ¬é¡¹ç›®ä¸»è¦æ¶‰åŠåŸºäº C/C++ è¯­è¨€çš„ STM32 ARM èŠ¯ç‰‡æ§åˆ¶ç®—æ³•ã€ç‰©è”ç½‘ç½‘å…³åè®®ï¼Œç”µå­é›†æˆç”µè·¯è®¾è®¡ï¼ŒåŸºäº Python è¯­è¨€çš„æ ‘è“æ´¾æ§åˆ¶ç®—æ³•ï¼Œç»“åˆ MySQL æ•°æ®åº“çš„ç”¨æˆ·è¡Œä¸ºåˆ†æ AI æœºå™¨å­¦ä¹ ç®—æ³•ã€‚
        description: |
          æœ¬é¡¹ç›®ä¸»è¦å¼€å‘äº†ä¸€ç§åŸºäºç”¨æˆ·è¡Œä¸ºåˆ†æçš„æ™ºèƒ½å®¶å±…èŠ‚èƒ½ç³»ç»Ÿã€‚ä½¿ç”¨é¢„æµ‹ç®—æ³•å®ç°å¯¹ç”¨æˆ·å®¶ç”µä½¿ç”¨è¡Œä¸ºçš„é¢„æµ‹ï¼Œæå‡ºä¸€ç§å®¤å†…å®¶ç”µè¿è¡Œè°ƒåº¦ç®—æ³•ï¼Œåœ¨ä¿éšœç”¨æˆ·èˆ’é€‚åº¦çš„å‰æä¸‹ï¼Œé€šè¿‡å¯¹ç”µå™¨è¿ä½œçŠ¶æ€çš„åŠ¨æ€è§„åˆ’ï¼Œæœ‰æ•ˆæé«˜èƒ½æºçš„åˆ©ç”¨æ•ˆç‡ï¼Œå‡å°‘ç”¨æˆ·çš„ç”µåŠ›æ”¯å‡ºï¼Œè¾¾åˆ°èŠ‚èƒ½çš„ç›®çš„ã€‚

          ä¸ºäº†å®ç°å¯¹å®¶ç”¨ç”µæ°”çš„éä¾µå…¥å¼çŠ¶æ€æ£€æµ‹å’Œæ•´å±‹å®¶ç”¨ç”µæ°”çš„å…¨å±€çŠ¶æ€åˆ†æï¼Œæˆ‘ä»¬è‡ªè¡Œç ”å‘äº†ä¸€æ¬¾åŸºäºæ— çº¿æ™ºèƒ½ç½‘å…³çš„æ™ºèƒ½å®¶å±…èŠ‚èƒ½ç³»ç»Ÿï¼Œé€šè¿‡é‡‡ç”¨èƒ½è€—é‡‡é›†æ¨¡å—å’Œä¼ æ„Ÿå™¨ç›‘æµ‹æ¨¡å—å¯¹ç”µå™¨çš„ç”¨ç”µæƒ…å†µå’Œä½¿ç”¨ç¯å¢ƒä¿¡æ¯è¿›è¡Œé‡‡é›†ï¼Œåœ¨æœ¬åœ°èŠ‚ç‚¹å¯¹ç”µå™¨èƒ½è€—ä¿¡æ¯è¿›è¡Œç®€å•çš„å¤„ç†åï¼Œé€šè¿‡ZigBeeæ— çº¿é€šä¿¡æ¨¡å—å°†ç”¨ç”µæƒ…å†µå‘é€ç»™æ™ºèƒ½ç½‘å…³è¿›è¡Œç”µå™¨è¯†åˆ«å’Œç”¨æˆ·è¡Œä¸ºåˆ†æå­¦ä¹ ï¼Œå¹¶å°†è®¡ç®—å‡ºæ¥çš„æ§åˆ¶ä¿¡æ¯åé¦ˆç»™æ§åˆ¶æ¨¡å—ï¼Œå¯¹ç”µå™¨çŠ¶æ€è¿›è¡Œç›¸åº”çš„æ™ºèƒ½æ§åˆ¶ã€‚åŒæ—¶ï¼Œå°†ç”µå™¨çš„èƒ½è€—ä¿¡æ¯å’Œæ“ä½œçŠ¶æ€é€šè¿‡äº‘å¹³å°åé¦ˆç»™ç”¨æˆ·ã€‚

          åŸºäºè¯¥é¡¹ç›®ï¼Œæˆ‘ä»¬è¿˜å‘è¡¨æœ‰ä¸¤ç¯‡è®¡ç®—æœºè½¯ä»¶è‘—ä½œï¼š[ã€ŠåŸºäºç”¨æˆ·è¡Œä¸ºåˆ†æçš„æ™ºèƒ½å®¶å±…èŠ‚èƒ½ç³»ç»Ÿã€‹](https://www.zhifufu.com/software/f6ce8a5266784156828b81667f7051b4.html)å’Œ[ã€Šç”µå™¨è¯†åˆ«å¯è§†åŒ–ç³»ç»Ÿã€‹](https://www.zhifufu.com/software/ef083d9c0ab2418fbba4cc709a46157f.html)ã€‚

          åŒæ—¶ï¼Œæˆ‘ä»¬ä¹Ÿæä¾›äº†è¯¥æ™ºèƒ½è°ƒèŠ‚ç³»ç»Ÿçš„æ¼”ç¤ºè§†é¢‘ï¼š[åŸºäºç”¨æˆ·è¡Œä¸ºåˆ†æçš„æ™ºèƒ½å®¶å±…èŠ‚èƒ½ç³»ç»Ÿ](https://www.bilibili.com/video/av27494462)ã€‚

      - layout: left
        title: åŸºäºè¯­éŸ³è¯†åˆ«çš„æ™ºèƒ½è€äººçœ‹æŠ¤ç³»ç»Ÿ
        sub_title: æµ™æ±Ÿçœæ–°è‹—äººæ‰è®¡åˆ’
        caption: 2017å¹´6æœˆè‡³2018å¹´10æœˆ
        quote: >
          è¯¥é¡¹ç›®ä¸»è¦æ¶‰åŠåŸºäº C/C++ è¯­è¨€çš„ STM32 ARM èŠ¯ç‰‡ã€å¾®èŠ¯ PLC18ã€STC51 èŠ¯ç‰‡å’Œæ ‘è“æ´¾çš„æ§åˆ¶ç®—æ³•ã€ç‰©è”ç½‘ç½‘å…³åè®®ï¼Œç”µå­é›†æˆç”µè·¯è®¾è®¡ï¼ŒåŸºäº JavaScript å’Œ JAVA è¯­è¨€çš„ç½‘ç«™å‰åç«¯å¼€å‘ï¼ŒåŸºäº MySQL è¯­è¨€çš„æ•°æ®åº“ï¼ŒåŸºäº Tensorflow è¯­è¨€çš„AIè‡ªç„¶è¯­è¨€å¤„ç†ç®—æ³•ã€‚
        description: |
          æœ¬é¡¹ç›®ä¸»è¦å¼€å‘äº†ä¸€ç§æ–°å‹åŸºäºè¯­éŸ³è¯†åˆ«çš„æ™ºèƒ½è€äººçœ‹æŠ¤ç³»ç»Ÿã€‚

          è¯¥ç³»ç»Ÿç”±æ™ºèƒ½ä¾¿æºå¼èƒ¸é’ˆå’Œæ™ºèƒ½å®¶åº­æ§åˆ¶ä¸­å¿ƒä¸¤éƒ¨åˆ†æ„æˆï¼Œæ™ºèƒ½èƒ¸é’ˆé™¤å®ç°åŸºæœ¬çš„è£…é¥°åŠŸèƒ½å¤–ï¼Œè¿˜èƒ½å¤Ÿå®ç°é˜²æ‘”å€’æé†’å’Œè·Œå€’æŠ¥è­¦ï¼Œå½“è€äººå°†è¦è·Œå€’æ—¶é€šè¿‡èƒ¸é’ˆä¸Šè‡ªå¸¦çš„æŠ¥è­¦æ¨¡å—å¯¹è€äººè¿›è¡Œé¢„è­¦æé†’ï¼›åˆ°è€äººè·Œå€’åœ¨åœ°éš¾ä»¥çˆ¬èµ·æ—¶ï¼Œé€šè¿‡æ™ºèƒ½å®¶åº­æ§åˆ¶ä¸­å¿ƒä»¥çŸ­ä¿¡çš„æ–¹å¼å®æ—¶å‘å­å¥³æŠ¥è­¦ã€‚é™¤æ­¤ä¹‹å¤–ï¼Œæ™ºèƒ½èƒ¸é’ˆè¿˜å…·æœ‰è¯­éŸ³ä¿¡å·é‡‡é›†çš„åŠŸèƒ½ï¼Œå°†é‡‡é›†åˆ°çš„ä¿¡å·é€šè¿‡æ— çº¿ä¼ è¾“åè®®å‘é€ç»™ä¸»æœºè¿›è¡Œå¤„ç†ã€‚

          æ™ºèƒ½å®¶åº­æ§åˆ¶ä¸­å¿ƒä¸»è¦åšçš„æ˜¯è¯­éŸ³ä¿¡å·å¤„ç†å’Œæ™ºèƒ½å®¶åº­æ§åˆ¶ï¼Œå¹¶æ·»åŠ è¿œç¨‹æ™ºèƒ½æ‘„åƒå¤´ï¼Œè®©å­å¥³èƒ½å¤Ÿå®æ—¶ç›‘æ§å®¶åº­å®‰å…¨ã€‚ä»æœºçš„æ— çº¿éº¦å…‹é£é˜µåˆ—é‡‡é›†åˆ°çš„ç»è¿‡å‰ç«¯é™å™ªå¤„ç†çš„è¯­éŸ³é€šè¿‡åœ¨ä¸»æœºä¸Šè¿›è¡Œæ±‰è¯­å£éŸ³è‡ªé€‚åº”å¤„ç†ã€éå‘½ä»¤è¯æ™ºèƒ½è¯­ä¹‰åˆ†æåå¾—åˆ°ç²¾ç¡®çš„æŒ‡ä»¤ä¿¡æ¯ï¼Œæ§åˆ¶ä¸»æœºå®ç°å¯¹äºç›¸åº”çš„æ™ºèƒ½å®¶å±…çš„æ§åˆ¶ã€‚

          åŸºäºè¯¥é¡¹ç›®ï¼Œæˆ‘ä»¬è¿˜å‘è¡¨æœ‰ä¸¤ç¯‡è®¡ç®—æœºè½¯ä»¶è‘—ä½œï¼š[ã€ŠåŸºäºè¯­éŸ³è¯†åˆ«çš„æ™ºèƒ½è€äººçœ‹æŠ¤ç³»ç»Ÿã€‹](https://www.zhifufu.com/software/cdc73b89bcd843ed93816efe8788d86f.html)å’Œ[ã€ŠåŸºäºæ— çº¿è‡ªç»„ç½‘åè®®çš„å®¶ç”µæ§åˆ¶ç³»ç»Ÿã€‹](https://www.zhifufu.com/software/ecb05294e01e4abba97e5e185e0e22d6.html)ã€‚

          åŒæ—¶ï¼Œæˆ‘ä»¬ä¹Ÿæä¾›äº†è¯¥æ™ºèƒ½è€äººçœ‹æŠ¤ç³»ç»Ÿçš„æ¼”ç¤ºè§†é¢‘ï¼š[åŸºäºè¯­éŸ³è¯†åˆ«çš„æ™ºèƒ½è€äººçœ‹æŠ¤ç³»ç»Ÿ](https://www.bilibili.com/video/av81282247)ã€‚

      - layout: left
        title: åŸºäºSTM32çš„æ™ºèƒ½å„¿ç«¥çœ‹æŠ¤æ‰‹è¡¨
        sub_title: æ­å·ç”µå­ç§‘æŠ€å¤§å­¦èŠ¯è‹—äººæ‰è®¡åˆ’
        caption: 2016å¹´12æœˆè‡³2017å¹´12æœˆ
        quote: >
          æœ¬é¡¹ç›®ä¸»è¦æ¶‰åŠåŸºäº C/C++ è¯­è¨€çš„ STM32 èŠ¯ç‰‡æ§åˆ¶ç®—æ³•ï¼Œç”µå­é›†æˆç”µè·¯è®¾è®¡ã€‚
        description: |
          æœ¬é¡¹ç›®ä¸»è¦å¼€å‘äº†ä¸€æ¬¾é›†å„¿ç«¥å¥åº·å’Œå®‰å…¨ä¸¤ä¸ªæ–¹é¢äºä¸€ä½“çš„æ™ºèƒ½å„¿ç«¥çœ‹æŠ¤æ‰‹è¡¨ï¼Œä»¥ STM32 MCU ä½œä¸ºä¸»æ§èŠ¯ç‰‡, ç»“åˆå¤–å›´ç”µè·¯å’Œå¤šç§ä¼ æ„Ÿå™¨åŠ ä»¥å®ç°ã€‚æ ¹æ®ç›‘æŠ¤äººçš„å®é™…éœ€æ±‚ï¼Œè¯¥è®¾è®¡æ¶µç›–è¿åŠ¨æ£€æµ‹ã€ç¯å¢ƒç›‘æµ‹ã€GPSå®šä½ã€SOSæŠ¥è­¦å››å¤§æ–¹å‘å¹¶ä¸”å…·æœ‰è®°å½•å„¿ç«¥è¿åŠ¨æ­¥æ•°ã€GPSé‡‡é›†è¿åŠ¨é‡Œç¨‹ã€æ—¶é—´å’Œé€Ÿåº¦ã€æ¸©æ¹¿åº¦æ£€æµ‹ã€é›¾éœ¾æ£€æµ‹å’ŒæŠ¥è­¦ã€è®°å½•æ´»åŠ¨è·¯ç¨‹ã€è®¾ç½®ç”µå­æ …æ è¶…å‡ºèŒƒå›´çŸ­ä¿¡é€šçŸ¥å®¶é•¿ã€ä¸€é”®å‘¼å«å®¶é•¿ã€å‘å®¶é•¿å‘é€ç‰¹å®šçŸ­ä¿¡ç­‰å¤šé¡¹åŠŸèƒ½ã€‚

          è¯¥æ™ºèƒ½å„¿ç«¥çœ‹æŠ¤æ‰‹è¡¨çš„è®¾è®¡å……åˆ†è€ƒè™‘äº†å­©å­ç›‘æŠ¤äººçš„å®é™…éœ€æ±‚ï¼Œå¹¶é€šè¿‡ç”µå­æŠ€æœ¯çš„æ–¹æ³•åŠ ä»¥è§£å†³ã€‚

      - layout: left
        title: é˜²é›¾éœ¾ç©ºæ°”è°ƒèŠ‚æ™ºèƒ½ç›’å­
        sub_title: æ­å·ç”µå­ç§‘æŠ€å¤§å­¦èŠ¯è‹—äººæ‰è®¡åˆ’
        caption: 2016å¹´12æœˆè‡³2017å¹´12æœˆ
        quote: >
          æœ¬é¡¹ç›®æ¶‰åŠåŸºäº C/C++ è¯­è¨€çš„ STM32 èŠ¯ç‰‡æ§åˆ¶ç®—æ³•ã€ç‰©è”ç½‘ç½‘å…³åè®®ï¼Œç”µå­é›†æˆç”µè·¯è®¾è®¡ã€‚
        description: |
          æœ¬é¡¹ç›®ä¸»è¦å¼€å‘äº†ä¸€æ¬¾å°ä½“ç§¯çš„å…·æœ‰é˜²é›¾éœ¾åŠŸèƒ½çš„ç©ºæ°”è°ƒèŠ‚æ™ºèƒ½ç›’å­ã€‚å…·æœ‰ç›‘æµ‹å®¤å†…å¤–æ¸©åº¦ï¼Œç©ºæ°”æ¹¿åº¦ï¼ŒäºŒæ°§åŒ–ç¢³æµ“åº¦ä»¥åŠé¢—ç²’ç‰©æµ“åº¦ç­‰åŠŸèƒ½ï¼Œå¹¶å¯ä»¥æ ¹æ®è¿™äº›æŒ‡æ ‡çš„ç›‘æµ‹ç»“æœå¯¹æ•°æ®è¿›è¡Œåˆ†æï¼Œä»è€Œå®ç°åˆ¤æ–­æ˜¯å¦å­˜åœ¨é›¾éœ¾ä»¥åŠé›¾éœ¾æµ“åº¦æµ‹é‡åŠŸèƒ½ã€‚åŒæ—¶ï¼Œå¦‚æœç›‘æµ‹åˆ°æœ‰é›¾éœ¾è¶…è¿‡ä¸€å®šé‡çš„æµ“åº¦ï¼Œç›’å­è¿˜å¯ä»¥è‡ªåŠ¨è°ƒèŠ‚é—¨çª—å¼€å…³ã€‚

      - layout: left
        title: æ—‹è½¬æ–‡å­—æ˜¾ç¤ºLED
        sub_title: æ­å·ç”µå­ç§‘æŠ€å¤§å­¦èŠ¯è‹—äººæ‰è®¡åˆ’
        caption: 2016å¹´6æœˆè‡³2016å¹´7æœˆ
        quote: >
          æœ¬é¡¹ç›®ä¸»è¦æ¶‰åŠåŸºäº C/C++ è¯­è¨€çš„ STM32 èŠ¯ç‰‡æ§åˆ¶ç®—æ³•ï¼Œç”µå­é›†æˆç”µè·¯è®¾è®¡ã€‚
        description: |
          æœ¬é¡¹ç›®ä¸»è¦å¼€å‘äº†å…·æœ‰ä¸­è‹±æ–‡ã€å­—ç¬¦ç¬¦å·å’Œæµæ°´èŠ±çº¹æ ·å¼æ˜¾ç¤ºåŠŸèƒ½çš„æ—‹è½¬LEDç¯ï¼Œåˆ©ç”¨äººçœ¼çš„è§†è§‰æ®‹ç•™æ•ˆåº”ï¼Œè‡ªåŠ¨è°ƒèŠ‚LEDç¯ç®¡çš„æ—‹è½¬å‘¨æœŸæ—¶é—´ï¼Œä»¥åˆ©ç”¨ä¸€æ ¹é«˜é€Ÿæ—‹è½¬çš„ç¯ç®¡å®ç°æ•´ä½“åœ†å‘¨é¢çš„ç”»é¢æ’ä¹…æ˜¾ç¤ºã€‚

          ä¸ºäº†å®ç°å¯¹äºLEDç¯ç®¡çš„è½¬é€Ÿä¸æ˜¾ç¤ºæ®‹ç•™æ—¶é•¿çš„ååŒæ§åˆ¶ï¼Œé€šè¿‡åœ¨LEDç¯ç®¡ä¸‹æ–¹å’Œå°ç¯åº•åº§ä¸Šæ–¹å®‰è£…çº¢å¤–å¯¹æ¥æ”¶å‘è®¾å¤‡ï¼ŒLEDç¯ç®¡ä¸Šçš„çº¢å¤–æ¥æ”¶ç®¡æ¯è½¬åŠ¨ä¸€åœˆå°±ä¼šå¯¼é€šä¸€æ¬¡ï¼Œè®©å•ç‰‡æœºçŸ¥é“ä»å“ªä¸€ç‚¹å¼€å§‹æ’­æ”¾å­—ç¬¦æˆ–è€…å›¾è±¡å…·æœ‰å¾ˆé«˜çš„æ¬£èµä»·å€¼ã€‚

          åŒæ—¶ï¼Œæˆ‘ä»¬ä¹Ÿæä¾›äº†è¯¥æ—‹è½¬æ–‡å­—æ˜¾ç¤ºLEDçš„å®ç°æºä»£ç å’Œç”µå­é›†æˆç”µè·¯è®¾è®¡ç‰ˆå›¾ï¼š[shaonianruntu/Rotating-LED](https://github.com/shaonianruntu/Rotating-LED) ä»¥åŠæ¼”ç¤ºè§†é¢‘ï¼š[æ—‹è½¬æ–‡å­—æ˜¾ç¤ºLED](https://www.bilibili.com/video/BV12s411K7yK)ã€‚

  - title: å·¥ä½œç»å† # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: æ­å·èŸè§†ç§‘æŠ€æœ‰é™å…¬å¸
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: æ•™è‚²èƒŒæ™¯ # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: æ­å·ç”µå­ç§‘æŠ€å¤§å­¦
        caption: 2019å¹´9æœˆè‡³ä»Š
        sub_title: è®¡ç®—æœºç§‘å­¦ä¸æŠ€æœ¯ç¡•å£«å­¦ä½
        quote: >
          æ­å·ç”µå­ç§‘æŠ€å¤§å­¦ï¼ˆæ­ç”µï¼ŒHDUï¼‰æˆç«‹äº1956å¹´ï¼Œæ˜¯ä¸€æ‰€ç”µå­ä¿¡æ¯ç‰¹è‰²çªå‡ºï¼Œç»ç®¡å­¦ç§‘ä¼˜åŠ¿æ˜æ˜¾çš„æ•™å­¦ç ”ç©¶å‹ç»¼åˆæ€§å¤§å­¦ã€‚
        description:
          During my time at HDU I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a laboratory member of the [**Media Intelligence Laboratory**](http://mil.hdu.edu.cn/) and doing research in computer vision.

      - layout: left
        title: æ­å·ç”µå­ç§‘æŠ€å¤§å­¦
        caption: 2015å¹´9æœˆè‡³2019å¹´6æœˆ
        sub_title: è®¡ç®—æœºç§‘å­¦ä¸æŠ€æœ¯å­¦å£«å­¦ä½
        quote: >
          æ­å·ç”µå­ç§‘æŠ€å¤§å­¦ï¼ˆHDUï¼‰æˆç«‹äº1956å¹´ï¼Œæ˜¯ä¸€æ‰€ç”µå­ä¿¡æ¯ç‰¹è‰²çªå‡ºï¼Œç»ç®¡å­¦ç§‘ä¼˜åŠ¿æ˜æ˜¾çš„æ•™å­¦ç ”ç©¶å‹ç»¼åˆæ€§å¤§å­¦ã€‚
        description: |
          During my time at HDU I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I joint the **Hangzhou Dianzi University Microchip Joint Technological Innovation Incubation Laboratory** in my freshman year. And after that I worked with the lab's team members to complete some projects, particated in some competitions, and achieved some good results. I am mainly repsonible for some code writing work in the team projects and taking on role as **Head of Software Group**. In my laboratory time, I led my team members finshed **four college-level new seedling project**, **one provincial-level new seedling talent project**, **one national-level university student innovation and entrepreneurship project** as the role of team leader of these projects, and published a total of **four computer software copyrights**. 

          The experience in the laboratory allowed me to be in touch with some research projects and related professional knowledge earlier than other students. It also broadened my horizons and improved my self-learning ability and information gathering ability.

      - layout: left
        title: æµ™æ±Ÿçœä½™å§šä¸­å­¦
        caption: 2012 - 2015
        quote: >
          æµ™æ±Ÿçœä½™å§šä¸­å­¦ï¼Œæ˜¯ä¸€æ‰€ä½äºä¸­å›½å®æ³¢å¸‚ä½™å§šå¸‚çš„é‡ç‚¹é«˜ä¸­ã€‚è¯¥æ ¡åˆ›å»ºäº1935å¹´ï¼Œæ˜¯ä½™å§šå†å²ä¸Šç¬¬ä¸€æ‰€ä¸­å­¦ï¼Œåˆå»ºæ—¶ä»…æœ‰åˆä¸­éƒ¨ï¼Œ1943å¹´èµ·å¼€è®¾é«˜ä¸­ã€‚1961å¹´è¯¥æ ¡æˆä¸ºæµ™æ±Ÿçœè¯•ç‚¹ä¸­å­¦ï¼Œ1981å¹´æˆä¸ºæµ™æ±Ÿçœé‡ç‚¹ä¸­å­¦ã€‚1989å¹´åæˆä¸ºä¸“é—¨é«˜ä¸­ï¼Œ1995å¹´æˆä¸ºæµ™æ±Ÿçœä¸€çº§é‡ç‚¹ä¸­å­¦
        description: |

  - title: è·å¥–ç»å†
    layout: text
    content: |
      - 2014/07/12: å›½å®¶å¥–å­¦é‡‘
      - 2015/11/13: æµ™æ±Ÿçœæ–°è‹—äººæ‰è®¡åˆ’
      - 2018/11/12: å›½å®¶çº§è‡ªç„¶ç§‘å­¦åŸºé‡‘

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in machine learing and software engineering some of my other interests and hobbies are:
      - Classical literture & Swordsman fiction
      - Historical drama & Costume drama
      - Drive & Travel

      This is my Douban account [shaonianruntu](https://www.douban.com/people/shaonianruntu/). If you have the same interest, maybe we can be a book friend.

      Here is the link to some of my friends' homepages, maybe you will be interested:
        - [é«˜é£è€å¸ˆ](https://fei-hdu.github.io/)
        - [ç½—å®‡çŸ—åŒå­¦](https://www.luoyuchu.com/)
        - [å¶å®¶è±ªåŒå­¦](https://yjhmelody.github.io/)
        - [æ›¹éªå¨å­¦å¼Ÿ](https://accepteddoge.com/)
        - [æŸ³å©¼å­¦å§](https://www.liuchuo.net/)

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
